### ISSUE TITLE
Q: SIMD functions

### ISSUE THREAD

**Issue by ib00** [bkaradzic/bx#324]
Some "simd_t.h" questions:

1. What's the difference between simd_selb() and simd_sels() functions?
2. What are the functions with _ni suffix?

Thanks.

**Comment by bkaradzic** [comment]
1.

 `*_sels` creates mask based on signed bit, so if signed bit is set it will have mask, otherwise mask will be 0.

 `*_selb` just uses mask provided.

2.

 `*_ni` stands for non intrisics. Meaning implementation might consist of 2 or more intrisics operations.

Please use Discussions, or Discord (of bgfx project) for questions, not issues.
