### ISSUE TITLE
Building on musl

### ISSUE THREAD

**Issue by ismaell** [bkaradzic/bx#329]
I'm trying to build MAME for a musl libc based host, and I found out that the support in bx was removed; ok,that's trivial, but I now realise that bx is shipping binaries and that must be get rid of (no host executables distribution policy).

Would you be willing to cooperate on getting bx up to modern unix software packaging standards?

I would just like to get a clean package for Linux and BSD, that is portable without explicit scaffolding and easy for analysis,  meaning specially no binaries; but it's perfectly fine if the repo isn't by itself clean, as long as the cleanup can be automated.

**Comment by bkaradzic** [comment]
In your case MAME, you should not think of bgfx/bimg/bx as 3 packages, rather one. You should basically fork repos, organize files as you wish, delete things you don't need, etc. all with some automated script, so you can get to that state from newer versions of repo. If you need more platforms, CRT libs, etc. that what's provided currently you need to patch it yourself.

**Comment by ismaell** [comment]
I meant to integrate that upstream, as I'm not involved with MAME, just packaging it and  trying to make it comply  with OS policies, which includes it's upstreams.

**Comment by bkaradzic** [comment]
- BX_CRT_MUSL is removed from bx because there is no way to detect it with define, and external define has to be set.
- BSD support is removed from bx because there is no maintainers for it.

The rest of things you mentioned is just adding arbitrary constraints from other projects, that are completely irrelevant for this project.

**Comment by ismaell** [comment]
Understood.

As for the musl point, just FYI, the "don't use macros for detection" doctrine is well funded, and it's the official policy of several projects (despite many still providing macros), including the GNU project; it has the advantage that when a new API becomes available it's detected without any intervention, and the detection is by nature uncoupled... but ultimately if it isn't up to your taste we're stuck with maintaining  patches on the side :(.

**Comment by bkaradzic** [comment]
> As for the musl point, just FYI, the "don't use macros for detection" doctrine is well founded,

With musl it just says "Unknown BX_CRT", I think...

**Comment by bkaradzic** [comment]
> the "don't use macros for detection" doctrine is well founded

The issue is that when diagnosing bugs/issues, it's actually super helpful to know build environment from compiler POV.

Like dumping string like this inside assert/error messages is very helpful:
`Compiler: GCC 11.4.0, CPU: x86, Architecture: 64-bit, OS: Linux, CRT: GNU C Library, C++: C++17, Date: Jun 16 2024, Time: 15:01:12`

Their doctrine/justification is about standard, and not using defines to do something in the code, and from my POV it's about diagnostics.

**Comment by ismaell** [comment]
Well,  autoconf's target triplets system solves the API part of this.

But both approaches are insufficient for diagnostics; e.g. on `musl` systems you can have applications compiled  against `glibc` but running against  a combination of  `musl` and `libgcompat`, something this approach would report as glibc. Even just a glibc upgrade at runtime can change the behaviour of the ABI, so version would matter as well.

Would it make sense to rely on another library for run-time CRT identification?
