### ISSUE TITLE
GLFW example and bgfx::renderFrame();

### ISSUE THREAD

**Issue by zlash** [bkaradzic/bx#63]
I've been toying around following the glfw example and found that to make it work a call to "bgfx::renderFrame()" is needed before calling _main_. 

I'm missing out something or is this supposed to work this way?  Is there any other considerations to take into account?

Thanks!

**Comment by bkaradzic** [comment]
It depends on threading of your application, more info here:
https://bkaradzic.github.io/bgfx/bgfx.html#platform-specific

Generally if you doing windowing, you should take care of render thread, since each platform has it's own rules for it. You can see examples of windowing for different platforms in examples/common/entry directory.
